cBnivL = {}
local gl = GetLocale()

if gl == "deDE" then
	cBnivL.Bags = "Bags"
	cBnivL.ResetNew = "Reset New"
    cBnivL.Search = "Suchen"
    cBnivL.Armor = "Rüstung"
    cBnivL.Weapon = "Waffe"
    cBnivL.Gem = "Juwelen"
    cBnivL.Trades = "Handwerkswaren"
    cBnivL.Consumables = "Verbrauchbar"
    cBnivL.Quest = "Quest"
    cBnivL.MarkAsNew = "Als neu markieren"
    cBnivL.MarkAsKnown = "Als bekannt markieren"
    cBnivL.bagCaptions = {
        ["cBniv_Bank"] 			= "Bank",
        ["cBniv_BankSets"]	    = "Sets",
        ["cBniv_BankArmor"]		= "Waffen & Rüstung",
        ["cBniv_BankQuest"]		= "Quest Items",
        ["cBniv_BankTrade"]		= "Handwerkswaren",
        ["cBniv_BankCons"]		= "Verbrauchbar",
		["cBniv_Stuff"]			= "Cooles Zeugs",
        ["cBniv_Junk"]			= "Gerümpel",
		["cBniv_ItemSets"]	    = "Sets",
		["cBniv_Armor"]			= "Waffen & Rüstung",
        ["cBniv_Quest"]			= "Quest Items",
		["cBniv_Consumables"]	= "Verbrauchbar",
        ["cBniv_TradeGoods"]	= "Handwerkswaren",
		["cBniv_Bag"]			= "Inventar",
		["cBniv_NewItems"]		= "Neue Items",
    }
elseif gl == "zhTW" then
	cBnivL.Bags = "Bags"
	cBnivL.ResetNew = "Reset New"
    cBnivL.Search = "Search"
    cBnivL.Armor = "護甲"
    cBnivL.Weapon = "武器"
    cBnivL.Gem = "珠寶"
    cBnivL.Trades = "商品"
    cBnivL.Consumables = "消耗品"
    cBnivL.Quest = "任務"
    cBnivL.MarkAsNew = "Mark as New"
    cBnivL.MarkAsKnown = "Mark as Known"
    cBnivL.bagCaptions = {
        ["cBniv_Bank"]          = "銀行",
        ["cBniv_BankSets"]      = "套裝",
        ["cBniv_BankArmor"]		= "裝備",
        ["cBniv_BankQuest"]		= "任務物品",
        ["cBniv_BankTrade"]		= "商品",
        ["cBniv_BankCons"]		= "消耗品",
        ["cBniv_Stuff"]         = "施法材料",
        ["cBniv_Junk"]			= "Junk",
        ["cBniv_ItemSets"]      = "套裝",
        ["cBniv_Armor"]         = "裝備",
        ["cBniv_Quest"]         = "任務物品",
        ["cBniv_Consumables"]   = "消耗品",
        ["cBniv_TradeGoods"]    = "商品",
        ["cBniv_Bag"]           = "存貨",
        ["cBniv_NewItems"]      = "新增",
    }
elseif gl == "zhCN" then
	cBnivL.Bags = "Bags"
	cBnivL.ResetNew = "Reset New"
    cBnivL.Search = "Search"
    cBnivL.Armor = "护甲"
    cBnivL.Weapon = "武器"
    cBnivL.Gem = "珠宝"
    cBnivL.Trades = "商品"
    cBnivL.Consumables = "消耗品"
    cBnivL.Quest = "任务"
    cBnivL.MarkAsNew = "Mark as New"
    cBnivL.MarkAsKnown = "Mark as Known"
    cBnivL.bagCaptions = {
        ["cBniv_Bank"]          = "银行",
        ["cBniv_BankSets"]      = "套装",
        ["cBniv_BankArmor"]		= "装备",
        ["cBniv_BankQuest"]		= "任务物品",
        ["cBniv_BankTrade"]		= "商品",
        ["cBniv_BankCons"]		= "消耗品",
        ["cBniv_Stuff"]         = "施法材料",
        ["cBniv_Junk"]			= "Junk",
        ["cBniv_ItemSets"]      = "套装",
        ["cBniv_Armor"]         = "装备",
        ["cBniv_Quest"]         = "任务物品",
        ["cBniv_Consumables"]   = "消耗品",
        ["cBniv_TradeGoods"]    = "商品",
        ["cBniv_Bag"]           = "存货",
        ["cBniv_NewItems"]      = "新增",
    }
elseif gl == "koKR" then
	cBnivL.Bags = "Bags"
	cBnivL.ResetNew = "Reset New"
    cBnivL.Search = "Search"
    cBnivL.Armor = "방어구"
    cBnivL.Weapon = "무기"
    cBnivL.Gem = "보석"
    cBnivL.Trades = "직업용품"
    cBnivL.Consumables = "소비용품"
    cBnivL.Quest = "퀘스트"
    cBnivL.MarkAsNew = "Mark as New"
    cBnivL.MarkAsKnown = "Mark as Known"
    cBnivL.bagCaptions = {
        ["cBniv_Bank"]  		= "은행",
        ["cBniv_BankSets"]	    = "세트",
        ["cBniv_BankArmor"]		= "무기 & 방어구",
        ["cBniv_BankQuest"]		= "퀘스트",
        ["cBniv_BankTrade"]		= "직업용품",
        ["cBniv_BankCons"]		= "소비용품",
		["cBniv_Stuff"]	    	= "지정",
        ["cBniv_Junk"]			= "Junk",
		["cBniv_ItemSets"]	    = "세트",
		["cBniv_Armor"]		    = "무기 & 방어구",
		["cBniv_Quest"]		    = "퀘스트",
		["cBniv_Consumables"]	= "소비용품",
        ["cBniv_TradeGoods"]	= "직업용품",
		["cBniv_Bag"]		    = "가방",
		["cBniv_NewItems"]	    = "신규",
    }    
elseif gl == "ruRU" then
	cBnivL.Bags = "Сумки"
	cBnivL.ResetNew = "Сортировка"
    cBnivL.Search = "Поиск"
    cBnivL.Armor = "Доспехи"
    cBnivL.Weapon = "Оружие"
    cBnivL.Gem = "Самоцветы"
    cBnivL.Trades = "Хозяйственные товары"
    cBnivL.Consumables = "Расходуемые"
    cBnivL.Quest = "Задания"
    cBnivL.MarkAsNew = "Отметить новым"
    cBnivL.MarkAsKnown = "Mark as Known"
    cBnivL.bagCaptions = {
		["cBniv_Bank"] 			= "Банк",
        ["cBniv_BankSets"]	    = "Наборы экипировки",
        ["cBniv_BankArmor"]		= "Оружие и Доспехи",
        ["cBniv_BankQuest"]		= "Задания",
        ["cBniv_BankTrade"]		= "Хозяйственные товары",
        ["cBniv_BankCons"]		= "Расходуемые",
		["cBniv_Stuff"]			= "Интересные предметы",
        ["cBniv_Junk"]			= "Мусор",
		["cBniv_ItemSets"]	    = "Наборы экипировки",
		["cBniv_Armor"]			= "Оружие и Доспехи",
		["cBniv_Quest"]			= "Задания",
		["cBniv_Consumables"]	= "Расходуемые",
        ["cBniv_TradeGoods"]    = "Хозяйственные товары",
		["cBniv_Bag"]			= "Рюкзак",
		["cBniv_NewItems"]		= "Новые предметы",
    }
elseif gl == "frFR" then
	cBnivL.Bags = "Bags"
	cBnivL.ResetNew = "Reset New"
    cBnivL.Search = "Recherche"
    cBnivL.Armor = "Armure"
    cBnivL.Weapon = "Arme"
    cBnivL.Gem = "Gemme"
    cBnivL.Trades = "Artisanat"
    cBnivL.Consumables = "Consommable"
    cBnivL.Quest = "Qu\195\170te"
    cBnivL.MarkAsNew = "Marquer comme Neuf"
    cBnivL.MarkAsKnown = "Marquer comme Connu"
    cBnivL.bagCaptions = {
		["cBniv_Bank"] 			= "Banque",
        ["cBniv_BankSets"]	    = "Sets",
        ["cBniv_BankArmor"]		= "Armes et Armures",
        ["cBniv_BankQuest"]		= "Qu\195\170te",
        ["cBniv_BankTrade"]		= "Artisanat",
        ["cBniv_BankCons"]		= "Consommables",
		["cBniv_Stuff"]			= "Divers",
        ["cBniv_Junk"]			= "Gris",
		["cBniv_ItemSets"]	    = "Sets",
		["cBniv_Armor"]			= "Armes et Armures",
		["cBniv_Quest"]			= "Qu\195\170te",
		["cBniv_Consumables"]	= "Consommables",
        ["cBniv_TradeGoods"]    = "Artisanat",
		["cBniv_Bag"]			= "Inventaire",
		["cBniv_NewItems"]		= "Nouveaux Objets",
    }   
else
	cBnivL.Bags = "Bags"
	cBnivL.ResetNew = "Reset New"
    cBnivL.Search = "Search"
    cBnivL.Armor = "Armor"
    cBnivL.Weapon = "Weapon"
    cBnivL.Gem = "Gem"
    cBnivL.Trades = "Trade Goods"
    cBnivL.Consumables = "Consumable"
    cBnivL.Quest = "Quest"
    cBnivL.MarkAsNew = "Mark as New"
    cBnivL.MarkAsKnown = "Mark as Known"
    cBnivL.bagCaptions = {
        ["cBniv_Bank"] 			= "Bank",
        ["cBniv_BankSets"]	    = "Sets",
        ["cBniv_BankArmor"]		= "Weapons & Armor",
        ["cBniv_BankQuest"]		= "Quest Items",
        ["cBniv_BankTrade"]		= "Trade Goods",
        ["cBniv_BankCons"]		= "Consumables",
		["cBniv_Stuff"]			= "Cool Stuff",
        ["cBniv_Junk"]			= "Junk",
		["cBniv_ItemSets"]	    = "Sets",
		["cBniv_Armor"]			= "Weapons & Armor",
		["cBniv_Quest"]			= "Quest Items",
		["cBniv_Consumables"]	= "Consumables",
        ["cBniv_TradeGoods"]	= "Trade Goods",
		["cBniv_Bag"]			= "Inventory",
		["cBniv_NewItems"]		= "New Items",
    }	
end