local T, C, L, _ = unpack(select(2, ...))
if not T.classic or C.automation.open_items ~= true then return end

----------------------------------------------------------------------------------------
--	The best way to add or delete item is to go at www.wowhead.com, search for a item.
--	Example: A Sack of Coins -> http://www.wowhead.com/item=5335
--	Take the number ID at the end of the URL, and add it to the list
----------------------------------------------------------------------------------------
T.OpenItems = {
	[5335] = true,		-- A Sack of Coins
	[6307] = true,		-- Message in a Bottle
	[6351] = true,		-- Dented Crate
	[6352] = true,		-- Waterlogged Crate
	[6353] = true,		-- Small Chest
	[6356] = true,		-- Battered Chest
	[6357] = true,		-- Sealed Crate
	[6643] = true,		-- Bloated Smallfish
	[6645] = true,		-- Bloated Mud Snapper
	[6647] = true,		-- Bloated Catfish
	[8366] = true,		-- Bloated Trout
	[9276] = true,		-- Pirate's Footlocker
	[9363] = true,		-- Sparklematic-Wrapped Box
	[10752] = true,		-- Emerald Encrusted Chest
	[11024] = true,		-- Evergreen Herb Casing
	[11422] = true,		-- Goblin Engineer's Renewal Gift
	[11423] = true,		-- Gnome Engineer's Renewal Gift
	[11568] = true,		-- Torwa's Pouch
	[11617] = true,		-- Eridan's Supplies
	[11912] = true,		-- Package of Empty Ooze Containers
	[11937] = true,		-- Fat Sack of Coins
	[11938] = true,		-- Sack of Gems
	[11955] = true,		-- Bag of Empty Ooze Containers
	[11966] = true,		-- Small Sack of Coins
	[12122] = true,		-- Kum'isha's Junk
	[12339] = true,		-- Vaelan's Gift
	[13874] = true,		-- Heavy Crate
	[13881] = true,		-- Bloated Redgill
	[13891] = true,		-- Bloated Salmon
	[15876] = true,		-- Nathanos' Chest
	[15902] = true,		-- A Crazy Grab Bag
	[17685] = true,		-- Smokywood Pastures Sampler
	[17726] = true,		-- Smokywood Pastures Special Gift
	[17727] = true,		-- Smokywood Pastures Gift Pack
	[17962] = true,		-- Blue Sack of Gems
	[17963] = true,		-- Green Sack of Gems
	[17964] = true,		-- Gray Sack of Gems
	[17965] = true,		-- Yellow Sack of Gems
	[17969] = true,		-- Red Sack of Gems
	[18804] = true,		-- Lord Grayson's Satchel
	[19035] = true,		-- Lard's Special Picnic Basket
	[19150] = true,		-- Sentinel Basic Care Package
	[19151] = true,		-- Sentinel Standard Care Package
	[19152] = true,		-- Sentinel Advanced Care Package
	[19153] = true,		-- Outrider Advanced Care Package
	[19154] = true,		-- Outrider Basic Care Package
	[19155] = true,		-- Outrider Standard Care Package
	[19422] = true,		-- Darkmoon Faire Fortune
	[20228] = true,		-- Defiler's Advanced Care Package
	[20229] = true,		-- Defiler's Basic Care Package
	[20230] = true,		-- Defiler's Standard Care Package
	[20231] = true,		-- Arathor Advanced Care Package
	[20233] = true,		-- Arathor Basic Care Package
	[20236] = true,		-- Arathor Standard Care Package
	[20469] = true,		-- Decoded True Believer Clippings
	[20708] = true,		-- Tightly Sealed Trunk
	[20766] = true,		-- Slimy Bag
	[20767] = true,		-- Scum Covered Bag
	[20768] = true,		-- Oozing Bag
	[21113] = true,		-- Watertight Trunk
	[21150] = true,		-- Iron Bound Trunk
	[21156] = true,		-- Scarab Bag
	[21164] = true,		-- Bloated Rockscale Cod
	[21191] = true,		-- Carefully Wrapped Present
	[21216] = true,		-- Smokywood Pastures Extra-Special Gift
	[21228] = true,		-- Mithril Bound Trunk
	[21270] = true,		-- Gently Shaken Gift
	[21271] = true,		-- Gently Shaken Gift
	[21310] = true,		-- Gaily Wrapped Present
	[21315] = true,		-- Smokywood Satchel
	[21327] = true,		-- Ticking Present
	[21363] = true,		-- Festive Gift
	[21640] = true,		-- Lunar Festival Fireworks Pack
	[21746] = true,		-- Lucky Red Envelope
	[22746] = true,		-- Buccaneer's Uniform
	[23022] = true,		-- Curmudgeon's Payoff
}
