----------------------------------------------------------------------------------------
--	Binding keys for mouseover marking
----------------------------------------------------------------------------------------
BINDING_HEADER_TAR_MARK_HEADER = L_MISC_HEADER_MARK
BINDING_NAME_TAR_MARK_1 = BINDING_NAME_RAIDTARGET1
BINDING_NAME_TAR_MARK_2 = BINDING_NAME_RAIDTARGET2
BINDING_NAME_TAR_MARK_3 = BINDING_NAME_RAIDTARGET3
BINDING_NAME_TAR_MARK_4 = BINDING_NAME_RAIDTARGET4
BINDING_NAME_TAR_MARK_5 = BINDING_NAME_RAIDTARGET5
BINDING_NAME_TAR_MARK_6 = BINDING_NAME_RAIDTARGET6
BINDING_NAME_TAR_MARK_7 = BINDING_NAME_RAIDTARGET7
BINDING_NAME_TAR_MARK_8 = BINDING_NAME_RAIDTARGET8
BINDING_NAME_TAR_MARK_0 = BINDING_NAME_RAIDTARGETNONE